// title-data.js
const TITLE_DATA = [
    { level: 1, mascot: "🥚", title: "漢字タマゴ" },
    { level: 5, mascot: "🐣", title: "漢字ヒナ" },
    { level: 10, mascot: "🐤", title: "漢字ヒヨコ" },
    { level: 15, mascot: "🐥", title: "漢字コトリ" },
    { level: 20, mascot: "🐭", title: "漢字マウス" },
    { level: 25, mascot: "🐹", title: "漢字ハムスター" },
    { level: 30, mascot: "🐰", title: "漢字ウサギ" },
    { level: 35, mascot: "🦊", title: "漢字キツネ" },
    { level: 40, mascot: "🐱", title: "漢字ネコ" },
    { level: 45, mascot: "🐶", title: "漢字イヌ" },
    { level: 50, mascot: "🐵", title: "漢字サル" },
    { level: 55, mascot: "🐨", title: "漢字コアラ" },
    { level: 60, mascot: "🐼", title: "漢字パンダ" },
    { level: 65, mascot: "🐻", title: "漢字クマ" },
    { level: 70, mascot: "🐻‍❄️", title: "漢字シロクマ" },
    { level: 75, mascot: "🦁", title: "漢字ライオン" },
    { level: 80, mascot: "🐯", title: "漢字タイガー" },
    { level: 85, mascot: "🦅", title: "漢字ホーク" },
    { level: 90, mascot: "🦉", title: "漢字オウル" },
    { level: 95, mascot: "🦇", title: "漢字バット" },
    { level: 100, mascot: "🦄", title: "漢字ユニコーン" },
    { level: 105, mascot: "🐴", title: "漢字ホース" },
    { level: 110, mascot: "🐗", title: "漢字イノシシ" },
    { level: 115, mascot: "🐺", title: "漢字ウルフ" },
    { level: 120, mascot: "🦍", title: "漢字ゴリラ" },
    { level: 125, mascot: "🦏", title: "漢字サイ" },
    { level: 130, mascot: "🐘", title: "漢字ゾウ" },
    { level: 135, mascot: "🦕", title: "漢字ブラキオ" },
    { level: 140, mascot: "🦖", title: "漢字ティラノ" },
    { level: 145, mascot: "🐊", title: "漢字ワニ" },
    { level: 150, mascot: "🦈", title: "漢字シャーク" },
    { level: 155, mascot: "🐬", title: "漢字ドルフィン" },
    { level: 160, mascot: "🐳", title: "漢字ホエール" },
    { level: 165, mascot: "🐙", title: "漢字オクトパス" },
    { level: 170, mascot: "🦑", title: "漢字クラーケン" },
    { level: 175, mascot: "🦀", title: "漢字クラブ" },
    { level: 180, mascot: "🦂", title: "漢字スコーピオン" },
    { level: 185, mascot: "🕷️", title: "漢字スパイダー" },
    { level: 190, mascot: "🐍", title: "漢字スネーク" },
    { level: 195, mascot: "🐢", title: "漢字タートル" },
    { level: 200, mascot: "🧚", title: "漢字フェアリー" },
    { level: 205, mascot: "🧞", title: "漢字ジン" },
    { level: 210, mascot: "🧜", title: "漢字マーメイド" },
    { level: 215, mascot: "🧛", title: "漢字ヴァンパイア" },
    { level: 220, mascot: "🧟", title: "漢字ゾンビ" },
    { level: 225, mascot: "👻", title: "漢字ゴースト" },
    { level: 230, mascot: "👽", title: "漢字エイリアン" },
    { level: 235, mascot: "👾", title: "漢字インベーダー" },
    { level: 240, mascot: "🤖", title: "漢字ロボット" },
    { level: 245, mascot: "🎃", title: "漢字パンプキン" },
    { level: 250, mascot: "👹", title: "漢字オニ" },
    { level: 255, mascot: "👺", title: "漢字テング" },
    { level: 260, mascot: "🐉", title: "漢字ドラゴン" },
    { level: 265, mascot: "🐲", title: "漢字ワイバーン" },
    { level: 270, mascot: "🌋", title: "漢字ボルケーノ" },
    { level: 275, mascot: "🌪️", title: "漢字トルネード" },
    { level: 280, mascot: "🌊", title: "漢字オーシャン" },
    { level: 285, mascot: "🌲", title: "漢字ツリー" },
    { level: 290, mascot: "🌙", title: "漢字ムーン" },
    { level: 295, mascot: "☀️", title: "漢字サン" },
    { level: 300, mascot: "⭐", title: "漢字スター" },
    { level: 305, mascot: "🌟", title: "漢字コメット" },
    { level: 310, mascot: "🌠", title: "漢字メテオ" },
    { level: 315, mascot: "🌌", title: "漢字ギャラクシー" },
    { level: 320, mascot: "🪐", title: "漢字プラネット" },
    { level: 325, mascot: "🚀", title: "漢字ロケット" },
    { level: 330, mascot: "⚡", title: "漢字サンダー" },
    { level: 335, mascot: "❄️", title: "漢字ブリザード" },
    { level: 340, mascot: "🔥", title: "漢字フレイム" },
    { level: 345, mascot: "💧", title: "漢字アクア" },
    { level: 350, mascot: "🛡️", title: "漢字シールド" },
    { level: 355, mascot: "⚔️", title: "漢字ソード" },
    { level: 360, mascot: "🏹", title: "漢字アロー" },
    { level: 365, mascot: "🪄", title: "漢字マジック" },
    { level: 370, mascot: "🤴", title: "漢字キング" },
    { level: 375, mascot: "💎", title: "漢字ダイヤ" },
    { level: 380, mascot: "🔮", title: "漢字クリスタル" },
    { level: 385, mascot: "🧿", title: "漢字ビジョン" },
    { level: 390, mascot: "🔱", title: "漢字トライデント" },
    { level: 395, mascot: "⚜️", title: "漢字エンブレム" },
    { level: 400, mascot: "🥉", title: "漢字ブロンズ" },
    { level: 405, mascot: "🥈", title: "漢字シルバー" },
    { level: 410, mascot: "🥇", title: "漢字ゴールド" },
    { level: 415, mascot: "🏅", title: "漢字メダル" },
    { level: 420, mascot: "🏆", title: "漢字トロフィー" },
    { level: 425, mascot: "👑", title: "漢字クラウン" },
    { level: 430, mascot: "🌈", title: "漢字レインボー" },
    { level: 435, mascot: "🎇", title: "漢字スパーク" },
    { level: 440, mascot: "🦋", title: "漢字バタフライ" },
    { level: 445, mascot: "🪽", title: "漢字ウィング" },
    { level: 450, mascot: "👼", title: "漢字エンジェル" },
    { level: 455, mascot: "🦸", title: "漢字ヒーロー" },
    { level: 460, mascot: "🏯", title: "漢字キャッスル" },
    { level: 465, mascot: "🧠", title: "漢字ブレイン" },
    { level: 470, mascot: "💡", title: "漢字ジーニアス" },
    { level: 475, mascot: "🛸", title: "漢字UFO" },
    { level: 480, mascot: "🕳️", title: "漢字ブラックホール" },
    { level: 485, mascot: "⏳", title: "漢字タイム" },
    { level: 490, mascot: "♾️", title: "漢字インフィニティ" },
    { level: 495, mascot: "💮", title: "漢字レジェンド" },
    { level: 500, mascot: "🎓", title: "漢字マスター" }
];
